### ISSUE TITLE
Buscar pelo início do nome do navio

### ISSUE THREAD

**Issue by rodolfo-mendes** [wivsonmachado/praticagemSearch#1]
Seria interessante se a busca retornasse resultados digitando apenas o início do nome do navio. Por exemplo, digitando A retornar todos os navios que começam com A.

**Comment by wivsonmachado** [comment]
Bem observado Rodolfo, para quem não sabe nenhum nome de navio fica difícil usar o sistema, vou trabalhar nessa melhoria!
